import { RouteInfo } from './sidebar.metadata';

// @ts-ignore
// @ts-ignore
export const ROUTES: RouteInfo[] = [
  // {
  //   path: '',
  //   title: 'Personal',
  //   icon: '',
  //   class: 'nav-small-cap',
  //   label: '',
  //   labelClass: '',
  //   extralink: true,
  //   submenu: []
  // },
  {
    path: '/signin',
    title: 'LogIn',
    icon: 'mdi mdi-equal',
    class: '',
    label: '',
    labelClass: '',
    extralink: false,
    submenu: [],
    logged: false,
  },
  {
    path: '/signup',
    title: 'SignUp',
    icon: 'mdi mdi-arrange-bring-to-front',
    class: '',
    label: '',
    labelClass: '',
    extralink: false,
    submenu: [],
    logged: false,
  },
  {
    path: '/starter',
    title: 'Home',
    icon: 'mdi mdi-gauge',
    class: '',
    label: '',
    labelClass: '',
    extralink: false,
    submenu: [],
    logged: true,
  },
  {
    path: '/profile',
    title: 'PROFILE',
    icon: 'mdi mdi-toggle-switch',
    class: '',
    label: '',
    labelClass: '',
    extralink: false,
    submenu: [],
    logged: true,
  },

  {
    path: '/component/alert',
    title: 'Marketplace',
    icon: 'mdi mdi-message-bulleted',
    class: '',
    label: '',
    labelClass: '',
    extralink: false,
    submenu: [],
    logged: true,
  },
  {
    path: '/component/carousel',
    title: 'Invite',
    icon: 'mdi mdi-view-carousel',
    class: '',
    label: '',
    labelClass: '',
    extralink: false,
    submenu: [],
    logged: true,
  },

  // {
  //   path: '/component/modal',
  //   title: 'Modal',
  //   icon: 'mdi mdi-tablet',
  //   class: '',
  //   label: '',
  //   labelClass: '',
  //   extralink: false,
  //   submenu: []
  // },
  // {
  //   path: '/component/pagination',
  //   title: 'Pagination',
  //   icon: 'mdi mdi-backburger',
  //   class: '',
  //   label: '',
  //   labelClass: '',
  //   extralink: false,
  //   submenu: []
  // },
  // {
  //   path: '/component/poptool',
  //   title: 'Popover & Tooltip',
  //   icon: 'mdi mdi-image-filter-vintage',
  //   class: '',
  //   label: '',
  //   labelClass: '',
  //   extralink: false,
  //   submenu: []
  // },
  // {
  //   path: '/component/progressbar',
  //   title: 'Progressbar',
  //   icon: 'mdi mdi-poll',
  //   class: '',
  //   label: '',
  //   labelClass: '',
  //   extralink: false,
  //   submenu: []
  // },
  // {
  //   path: '/component/rating',
  //   title: 'Ratings',
  //   icon: 'mdi mdi-bandcamp',
  //   class: '',
  //   label: '',
  //   labelClass: '',
  //   extralink: false,
  //   submenu: []
  // },
  // {
  //   path: '/component/tabs',
  //   title: 'Tabs',
  //   icon: 'mdi mdi-sort-variant',
  //   class: '',
  //   label: '',
  //   labelClass: '',
  //   extralink: false,
  //   submenu: []
  // },
  // {
  //   path: '/component/timepicker',
  //   title: 'Timepicker',
  //   icon: 'mdi mdi-calendar-clock',
  //   class: '',
  //   label: '',
  //   labelClass: '',
  //   extralink: false,
  //   submenu: []
  // },
  // {
  //   path: '/component/buttons',
  //   title: 'Button',
  //   icon: 'mdi mdi-toggle-switch',
  //   class: '',
  //   label: '',
  //   labelClass: '',
  //   extralink: false,
  //   submenu: [],
  //   logged: true,
  // },
  // {
  //   path: '/component/cards',
  //   title: 'Card',
  //   icon: 'mdi mdi-blur-radial',
  //   class: '',
  //   label: '',
  //   labelClass: '',
  //   extralink: false,
  //   submenu: []
  // }
];
